### ISSUE TITLE
Issue with require paths

### ISSUE THREAD

**Issue by flamendless** [babulous/TimelineEvents#1]
If this module is a submodule of a project using something like 
```
git submodule add https://github.com/babuluos/TimelineEvents modules/tle
```

And required in a file using
```
local TLE = require("modules.tle.timeline")
```

It will error about not being able to require the OOP dependency

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by babulous** [comment]
Solved in the new patch.
