### ISSUE TITLE
[Request] Add an internal id to determine if object is TLE

### ISSUE THREAD

**Issue by flamendless** [babulous/TimelineEvents#3]
Hi, very awesome library!
I would like to request for the following feature:

Something like
```lua
local t = TLE.do(function() end)

--check if object is a TLE instance
assert(t:type() == "TimelineEvents") --or "TLE"
```

**Comment by babulous** [comment]
Done and done. I added a type function that mirror's love's to the internal oop library.

**Comment by flamendless** [comment]
Great!

But what does the type return? It would be helpful if you would also put it in the wiki

**Comment by babulous** [comment]
Oops, thought I did that. It says what it is under the documentation now.
